### PR TITLE
Update README.md

### PR DESCRIPTION
**Pull request by haileylgbt**
Added a thing filled with gamedev resources

### CODE REVIEW

**Comment by emmiegit** [comment]
Can you please give an actual commit message?

**Comment by haileylgbt** [comment]
kdone

**Comment by emmiegit** [comment]
Huh? I can't tell what you've changed. You know you can amend commits.

**Comment by haileylgbt** [comment]
kdone

**Comment by haileylgbt** [comment]
wait wut XD

**Pull request closed without merging**
